wandb_version: 1

_wandb:
  desc: null
  value:
    code_path: code/main.py
    python_version: 3.9.16
    cli_version: 0.15.3
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1686144606.325241
    t:
      1:
      - 1
      - 5
      - 6
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 6
      - 41
      - 53
      - 55
      3:
      - 15
      - 23
      4: 3.9.16
      5: 0.15.3
      8:
      - 2
      - 5
